---
title: "unemployment rate regression"
author: "Tingwen Hua"
date: "08/06/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

small rural without removing outline
```{r}
# load data
new_rural_small <- read.csv('sb_merged_unemployment_rate_rural_new.csv')

# linear regression model

unemployment_model1 <- lm(unemployment_rate ~ Percent.of.profitable.businesses*Total.number.of.businesses + Total.equity + Debt.to.equity.ratio..times., data= new_rural_small)
summary(unemployment_model1)

```

small rural with removing outline
```{r}
# load data
new_rural_small_rm <- read.csv('sb_merged_unemployment_rate_rm_rural_new.csv')

# linear regression model

unemployment_model2 <- lm(unemployment_rate ~ Percent.of.profitable.businesses*Total.number.of.businesses + Total.equity + Debt.to.equity.ratio..times., data= new_rural_small_rm)
summary(unemployment_model2)

```

small urban without removing outliers
```{r}
# load data
new_urban_small <- read.csv('sb_merged_unemployment_rate_urban_new.csv')

# linear regression model

unemployment_model3 <- lm(unemployment_rate ~ Percent.of.profitable.businesses*Total.number.of.businesses + Total.equity + Debt.to.equity.ratio..times., data= new_urban_small)
summary(unemployment_model3)


```
```{r}
# load data
new_urban_small_rm <- read.csv('sb_merged_unemployment_rate_rm_urban_new.csv')

# linear regression model

unemployment_model4 <- lm(unemployment_rate ~ Percent.of.profitable.businesses*Total.number.of.businesses + Total.equity + Debt.to.equity.ratio..times., data= new_urban_small_rm)
summary(unemployment_model4)


```

```{r}
# load data
new_rural_small <- read.csv('sb_merged_unemployment_rate_rural_new.csv')

new_rural_small$Total_No_Profitable <- new_rural_small$Percent.of.profitable.businesses* new_rural_small$Total.number.of.businesses

# linear regression model

unemployment_model8 <- lm(unemployment_rate ~ Total_No_Profitable +  Total.equity + Debt.to.equity.ratio..times., data= new_rural_small)
summary(unemployment_model8)

```